var searchData=
[
  ['randomaccessfiletest',['RandomAccessFileTest',['../classsimpledb_1_1file_1_1RandomAccessFileTest.html',1,'simpledb::file']]],
  ['recordcomparator',['RecordComparator',['../classsimpledb_1_1materialize_1_1RecordComparator.html',1,'simpledb::materialize']]],
  ['recordpage',['RecordPage',['../classsimpledb_1_1record_1_1RecordPage.html',1,'simpledb::record']]],
  ['recordtest',['RecordTest',['../classsimpledb_1_1record_1_1RecordTest.html',1,'simpledb::record']]],
  ['recoverymgr',['RecoveryMgr',['../classsimpledb_1_1tx_1_1recovery_1_1RecoveryMgr.html',1,'simpledb::tx::recovery']]],
  ['recoverytest',['RecoveryTest',['../classsimpledb_1_1tx_1_1recovery_1_1RecoveryTest.html',1,'simpledb::tx::recovery']]],
  ['remoteconnection',['RemoteConnection',['../interfacesimpledb_1_1jdbc_1_1network_1_1RemoteConnection.html',1,'simpledb::jdbc::network']]],
  ['remotedriver',['RemoteDriver',['../interfacesimpledb_1_1jdbc_1_1network_1_1RemoteDriver.html',1,'simpledb::jdbc::network']]],
  ['remotedriverimpl',['RemoteDriverImpl',['../classsimpledb_1_1jdbc_1_1network_1_1RemoteDriverImpl.html',1,'simpledb::jdbc::network']]],
  ['remotemetadata',['RemoteMetaData',['../interfacesimpledb_1_1jdbc_1_1network_1_1RemoteMetaData.html',1,'simpledb::jdbc::network']]],
  ['remotemetadataimpl',['RemoteMetaDataImpl',['../classsimpledb_1_1jdbc_1_1network_1_1RemoteMetaDataImpl.html',1,'simpledb::jdbc::network']]],
  ['remoteresultset',['RemoteResultSet',['../interfacesimpledb_1_1jdbc_1_1network_1_1RemoteResultSet.html',1,'simpledb::jdbc::network']]],
  ['remotestatement',['RemoteStatement',['../interfacesimpledb_1_1jdbc_1_1network_1_1RemoteStatement.html',1,'simpledb::jdbc::network']]],
  ['resultsetadapter',['ResultSetAdapter',['../classsimpledb_1_1jdbc_1_1ResultSetAdapter.html',1,'simpledb::jdbc']]],
  ['resultsetmetadataadapter',['ResultSetMetaDataAdapter',['../classsimpledb_1_1jdbc_1_1ResultSetMetaDataAdapter.html',1,'simpledb::jdbc']]],
  ['rid',['RID',['../classsimpledb_1_1record_1_1RID.html',1,'simpledb::record']]],
  ['rollbackrecord',['RollbackRecord',['../classsimpledb_1_1tx_1_1recovery_1_1RollbackRecord.html',1,'simpledb::tx::recovery']]]
];
